### ISSUE TITLE
Linked PonasKovas/miniquad-mandelbrot is broken

### ISSUE THREAD

**Issue by jgarvin** [not-fl3/miniquad#123]
Tried Linux and Windows with Firefox and Chrome, I just get a black screen following the link in the README.md.

**Comment by PonasKovas** [comment]
Oh boy

I have no idea, it doesn't work me too, and I haven't changed anything since the last time it worked.

If you check out https://github.com/PonasKovas/miniquad-mandelbrot-wasm-demo/commits/master you can see that it has absolutely no commits since they day I made it, and I swear it worked perfectly that day, and many days after.

**Comment by not-fl3** [comment]
yeah, the problem is with `gl.js` - it was updated a bit. 
To make it future-proof - better use some exact version of gl.js from miniquad-samples or host gl.js alongside with your html.
I believe something like`gl-0.2.20.js` or `gl-0.2.23.js` from miniquad-samples will do the job.

**Comment by PonasKovas** [comment]
Nah

Turns out I was pulling `gl.js` from my fork for some reason (https://github.com/PonasKovas/miniquad-mandelbrot-wasm-demo/blob/master/index.html#L23) and at some point I must have accidentally deleted that fork thinking that it wasn't doing anything anymore.

**Comment by PonasKovas** [comment]
Here I fixed it

**Comment by not-fl3** [comment]
Can confirm, it works now! :tada: 
Thanks!
