### ISSUE TITLE
Question regarding goals/non-goals - Metal/Vulkan/DX

### ISSUE THREAD

**Issue by simonrepp** [not-fl3/miniquad#43]
I was just wondering, if supporting Metal is "highly desirable" why is Vulkan/DirectX support then a non-goal? I understand that Apple has a very unique policy of not cooperating with any open and cross-platform graphics initiatives, but corporate and technical ethics aside, wouldn't just the addition of Metal put a very strange imbalance into the goals of what miniquad wants to be? (then being something "cutting edge" on macOS, and something perfectly fine but more like tried and tested on non-macOS platforms?) And in any case from what I understand OpenGL is just locked in at 4.1 on macOS, so technically I don't see a reason to not stick with OpenGL on macOS? (but I'm not firm with the macOS situation, so gladly correct me on that :))

Thanks for your work anyhow, the more frameworks the merrier, love to see all the initiatives. :) :+1:

**Comment by not-fl3** [comment]
OpenGL was deprecated in iOS 12, so going OpenGL only is not an option for modern IOS unfortunately.

**Comment by simonrepp** [comment]
I see, so the decision is for fear they will actually go one step ahead and remove OpenGL within a relevant amount of time? (although that is - to my understanding - right now pure speculation, isn't it?)

**Comment by not-fl3** [comment]
OpenGl was already deprecated since ios 12 and probably will be completely removed in ios 14. 
I did not release any games on ios for the last couple of years, but using native api's was a huge bonus for a store review process and probably notarization as well. 

All those factors make metal highly desirable target for mobile ios. 

Having directx as a native api on windows would be also nice, but not as important as metal.

**Comment by simonrepp** [comment]
Gotcha, makes sense now. If you have any pointers on where the probable removal plans were announced let me know, I'd be curious to do some further reading myself (but no worries if not :)) Thanks, have a good one!
